
package com.projeto1.aula02.servico;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "AviaoSibService", targetNamespace = "http://servico.avioes.projeto1.com/", wsdlLocation = "http://localhost:8086/servico/aviao?wsdl")
public class AviaoSibService
    extends Service
{

    private final static URL AVIAOSIBSERVICE_WSDL_LOCATION;
    private final static WebServiceException AVIAOSIBSERVICE_EXCEPTION;
    private final static QName AVIAOSIBSERVICE_QNAME = new QName("http://servico.avioes.projeto1.com/", "AviaoSibService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8086/servico/aviao?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AVIAOSIBSERVICE_WSDL_LOCATION = url;
        AVIAOSIBSERVICE_EXCEPTION = e;
    }

    public AviaoSibService() {
        super(__getWsdlLocation(), AVIAOSIBSERVICE_QNAME);
    }

    public AviaoSibService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AVIAOSIBSERVICE_QNAME, features);
    }

    public AviaoSibService(URL wsdlLocation) {
        super(wsdlLocation, AVIAOSIBSERVICE_QNAME);
    }

    public AviaoSibService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AVIAOSIBSERVICE_QNAME, features);
    }

    public AviaoSibService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AviaoSibService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AviaoSei
     */
    @WebEndpoint(name = "AviaoSibPort")
    public AviaoSei getAviaoSibPort() {
        return super.getPort(new QName("http://servico.avioes.projeto1.com/", "AviaoSibPort"), AviaoSei.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AviaoSei
     */
    @WebEndpoint(name = "AviaoSibPort")
    public AviaoSei getAviaoSibPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servico.avioes.projeto1.com/", "AviaoSibPort"), AviaoSei.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AVIAOSIBSERVICE_EXCEPTION!= null) {
            throw AVIAOSIBSERVICE_EXCEPTION;
        }
        return AVIAOSIBSERVICE_WSDL_LOCATION;
    }

}
